# Generated by Django 3.1.7 on 2021-03-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeetrackingsystem', '0003_auto_20210329_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
